/////////////////////////////////////////////////////////////////////////////
// Name:        ccamerapanel.h
// Purpose:     
// Author:      Anthemion Software Ltd
// Modified by: 
// Created:     20/04/2015 20:02:16
// RCS-ID:      
// Copyright:   (c) Anthemion Software Ltd
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/04/2015 20:02:16

#ifndef _CCAMERAPANEL_H_
#define _CCAMERAPANEL_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "ccamerapanel.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CCAMERAPANEL 10000
#define SYMBOL_CCAMERAPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_CCAMERAPANEL_TITLE _("cCameraPanel")
#define SYMBOL_CCAMERAPANEL_IDNAME ID_CCAMERAPANEL
#define SYMBOL_CCAMERAPANEL_SIZE wxSize(400, 300)
#define SYMBOL_CCAMERAPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * cCameraPanel class declaration
 */

class cCameraPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( cCameraPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    cCameraPanel();
    cCameraPanel( wxWindow* parent, wxWindowID id = SYMBOL_CCAMERAPANEL_IDNAME, const wxPoint& pos = SYMBOL_CCAMERAPANEL_POSITION, const wxSize& size = SYMBOL_CCAMERAPANEL_SIZE, long style = SYMBOL_CCAMERAPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CCAMERAPANEL_IDNAME, const wxPoint& pos = SYMBOL_CCAMERAPANEL_POSITION, const wxSize& size = SYMBOL_CCAMERAPANEL_SIZE, long style = SYMBOL_CCAMERAPANEL_STYLE );

    /// Destructor
    ~cCameraPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin cCameraPanel event handler declarations

////@end cCameraPanel event handler declarations

////@begin cCameraPanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end cCameraPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin cCameraPanel member variables
////@end cCameraPanel member variables
};

#endif
    // _CCAMERAPANEL_H_
