/////////////////////////////////////////////////////////////////////////////
// Name:        ccamerapanel.cpp
// Purpose:     
// Author:      Anthemion Software Ltd
// Modified by: 
// Created:     20/04/2015 20:02:16
// RCS-ID:      
// Copyright:   (c) Anthemion Software Ltd
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/04/2015 20:02:16

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "ccamerapanel.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "ccamerapanel.h"

////@begin XPM images
////@end XPM images


/*!
 * cCameraPanel type definition
 */

IMPLEMENT_DYNAMIC_CLASS( cCameraPanel, wxPanel )


/*!
 * cCameraPanel event table definition
 */

BEGIN_EVENT_TABLE( cCameraPanel, wxPanel )

////@begin cCameraPanel event table entries
////@end cCameraPanel event table entries

END_EVENT_TABLE()


/*!
 * cCameraPanel constructors
 */

cCameraPanel::cCameraPanel()
{
    Init();
}

cCameraPanel::cCameraPanel( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, pos, size, style);
}


/*!
 * cCameraPanel creator
 */

bool cCameraPanel::Create( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
////@begin cCameraPanel creation
    SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    wxPanel::Create( parent, id, pos, size, style );

    CreateControls();
    Centre();
////@end cCameraPanel creation
    return true;
}


/*!
 * cCameraPanel destructor
 */

cCameraPanel::~cCameraPanel()
{
////@begin cCameraPanel destruction
////@end cCameraPanel destruction
}


/*!
 * Member initialisation
 */

void cCameraPanel::Init()
{
////@begin cCameraPanel member initialisation
////@end cCameraPanel member initialisation
}


/*!
 * Control creation for cCameraPanel
 */

void cCameraPanel::CreateControls()
{    
////@begin cCameraPanel content construction
////@end cCameraPanel content construction
}


/*!
 * Should we show tooltips?
 */

bool cCameraPanel::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap cCameraPanel::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin cCameraPanel bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end cCameraPanel bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon cCameraPanel::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin cCameraPanel icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end cCameraPanel icon retrieval
}
