/////////////////////////////////////////////////////////////////////////////
// Name:        cdatepanel.cpp
// Purpose:     
// Author:      Anthemion Software Ltd
// Modified by: 
// Created:     20/04/2015 17:55:25
// RCS-ID:      
// Copyright:   (c) Anthemion Software Ltd
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/04/2015 17:55:25

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "cdatepanel.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "cdatepanel.h"

////@begin XPM images
////@end XPM images


/*!
 * cDatePanel type definition
 */

IMPLEMENT_DYNAMIC_CLASS( cDatePanel, wxPanel )


/*!
 * cDatePanel event table definition
 */

BEGIN_EVENT_TABLE( cDatePanel, wxPanel )

////@begin cDatePanel event table entries
////@end cDatePanel event table entries

END_EVENT_TABLE()


/*!
 * cDatePanel constructors
 */

cDatePanel::cDatePanel()
{
    Init();
}

cDatePanel::cDatePanel( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, pos, size, style);
}


/*!
 * cDatePanel creator
 */

bool cDatePanel::Create( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
////@begin cDatePanel creation
    SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    wxPanel::Create( parent, id, pos, size, style );

    CreateControls();
    Centre();
////@end cDatePanel creation
    return true;
}


/*!
 * cDatePanel destructor
 */

cDatePanel::~cDatePanel()
{
////@begin cDatePanel destruction
////@end cDatePanel destruction
}


/*!
 * Member initialisation
 */

void cDatePanel::Init()
{
////@begin cDatePanel member initialisation
////@end cDatePanel member initialisation
}


/*!
 * Control creation for cDatePanel
 */

void cDatePanel::CreateControls()
{    
////@begin cDatePanel content construction
////@end cDatePanel content construction
}


/*!
 * Should we show tooltips?
 */

bool cDatePanel::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap cDatePanel::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin cDatePanel bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end cDatePanel bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon cDatePanel::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin cDatePanel icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end cDatePanel icon retrieval
}
