/////////////////////////////////////////////////////////////////////////////
// Name:        cdatepanel.h
// Purpose:     
// Author:      Anthemion Software Ltd
// Modified by: 
// Created:     20/04/2015 17:55:25
// RCS-ID:      
// Copyright:   (c) Anthemion Software Ltd
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/04/2015 17:55:25

#ifndef _CDATEPANEL_H_
#define _CDATEPANEL_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "cdatepanel.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CDATEPANEL 10000
#define SYMBOL_CDATEPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_CDATEPANEL_TITLE _("cDatePanel")
#define SYMBOL_CDATEPANEL_IDNAME ID_CDATEPANEL
#define SYMBOL_CDATEPANEL_SIZE wxSize(400, 300)
#define SYMBOL_CDATEPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * cDatePanel class declaration
 */

class cDatePanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( cDatePanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    cDatePanel();
    cDatePanel( wxWindow* parent, wxWindowID id = SYMBOL_CDATEPANEL_IDNAME, const wxPoint& pos = SYMBOL_CDATEPANEL_POSITION, const wxSize& size = SYMBOL_CDATEPANEL_SIZE, long style = SYMBOL_CDATEPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CDATEPANEL_IDNAME, const wxPoint& pos = SYMBOL_CDATEPANEL_POSITION, const wxSize& size = SYMBOL_CDATEPANEL_SIZE, long style = SYMBOL_CDATEPANEL_STYLE );

    /// Destructor
    ~cDatePanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin cDatePanel event handler declarations

////@end cDatePanel event handler declarations

////@begin cDatePanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end cDatePanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin cDatePanel member variables
////@end cDatePanel member variables
};

#endif
    // _CDATEPANEL_H_
