/////////////////////////////////////////////////////////////////////////////
// Name:        cenforcementpanel.h
// Purpose:     
// Author:      Anthemion Software Ltd
// Modified by: 
// Created:     20/04/2015 19:38:38
// RCS-ID:      
// Copyright:   (c) Anthemion Software Ltd
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/04/2015 19:38:38

#ifndef _CENFORCEMENTPANEL_H_
#define _CENFORCEMENTPANEL_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "cenforcementpanel.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CENFORCEMENTPANEL 10000
#define ID_PANEL 10001
#define ID_PANEL3 10016
#define ID_PANEL4 10017
#define ID_PANEL5 10018
#define ID_PANEL2 10011
#define ID_PANEL6 10019
#define ID_PANEL7 10002
#define ID_PANEL8 10012
#define ID_BUTTON_DONE 10005
#define ID_PANEL1 10003
#define SYMBOL_CENFORCEMENTPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_CENFORCEMENTPANEL_TITLE _("cEnforcementPanel")
#define SYMBOL_CENFORCEMENTPANEL_IDNAME ID_CENFORCEMENTPANEL
#define SYMBOL_CENFORCEMENTPANEL_SIZE wxSize(400, 300)
#define SYMBOL_CENFORCEMENTPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * cEnforcementPanel class declaration
 */

class cEnforcementPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( cEnforcementPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    cEnforcementPanel();
    cEnforcementPanel( wxWindow* parent, wxWindowID id = SYMBOL_CENFORCEMENTPANEL_IDNAME, const wxPoint& pos = SYMBOL_CENFORCEMENTPANEL_POSITION, const wxSize& size = SYMBOL_CENFORCEMENTPANEL_SIZE, long style = SYMBOL_CENFORCEMENTPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CENFORCEMENTPANEL_IDNAME, const wxPoint& pos = SYMBOL_CENFORCEMENTPANEL_POSITION, const wxSize& size = SYMBOL_CENFORCEMENTPANEL_SIZE, long style = SYMBOL_CENFORCEMENTPANEL_STYLE );

    /// Destructor
    ~cEnforcementPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin cEnforcementPanel event handler declarations

////@end cEnforcementPanel event handler declarations

////@begin cEnforcementPanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end cEnforcementPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin cEnforcementPanel member variables
    wxStaticText* m_textNumber;
    wxStaticText* m_textTime;
    wxStaticText* m_textSpeed;
    wxStaticText* m_captureSpeed;
    wxStaticText* m_captureDistance;
////@end cEnforcementPanel member variables
};

#endif
    // _CENFORCEMENTPANEL_H_
