/////////////////////////////////////////////////////////////////////////////
// Name:        coperatorpanel.h
// Purpose:     
// Author:      Anthemion Software Ltd
// Modified by: 
// Created:     16/04/2015 18:14:19
// RCS-ID:      
// Copyright:   (c) Anthemion Software Ltd
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 16/04/2015 18:14:19

#ifndef _COPERATORPANEL_H_
#define _COPERATORPANEL_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "coperatorpanel.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_COPERATORPANEL 10000
#define SYMBOL_COPERATORPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_COPERATORPANEL_TITLE _("cOperatorPanel")
#define SYMBOL_COPERATORPANEL_IDNAME ID_COPERATORPANEL
#define SYMBOL_COPERATORPANEL_SIZE wxSize(400, 300)
#define SYMBOL_COPERATORPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * cOperatorPanel class declaration
 */

class cOperatorPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( cOperatorPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    cOperatorPanel();
    cOperatorPanel( wxWindow* parent, wxWindowID id = SYMBOL_COPERATORPANEL_IDNAME, const wxPoint& pos = SYMBOL_COPERATORPANEL_POSITION, const wxSize& size = SYMBOL_COPERATORPANEL_SIZE, long style = SYMBOL_COPERATORPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_COPERATORPANEL_IDNAME, const wxPoint& pos = SYMBOL_COPERATORPANEL_POSITION, const wxSize& size = SYMBOL_COPERATORPANEL_SIZE, long style = SYMBOL_COPERATORPANEL_STYLE );

    /// Destructor
    ~cOperatorPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin cOperatorPanel event handler declarations

////@end cOperatorPanel event handler declarations

////@begin cOperatorPanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end cOperatorPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin cOperatorPanel member variables
////@end cOperatorPanel member variables
};

#endif
    // _COPERATORPANEL_H_
