/////////////////////////////////////////////////////////////////////////////
// Name:        coperatorpanel.cpp
// Purpose:     
// Author:      Anthemion Software Ltd
// Modified by: 
// Created:     16/04/2015 18:14:18
// RCS-ID:      
// Copyright:   (c) Anthemion Software Ltd
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 16/04/2015 18:14:18

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "coperatorpanel.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "coperatorpanel.h"

////@begin XPM images
////@end XPM images


/*!
 * cOperatorPanel type definition
 */

IMPLEMENT_DYNAMIC_CLASS( cOperatorPanel, wxPanel )


/*!
 * cOperatorPanel event table definition
 */

BEGIN_EVENT_TABLE( cOperatorPanel, wxPanel )

////@begin cOperatorPanel event table entries
////@end cOperatorPanel event table entries

END_EVENT_TABLE()


/*!
 * cOperatorPanel constructors
 */

cOperatorPanel::cOperatorPanel()
{
    Init();
}

cOperatorPanel::cOperatorPanel( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, pos, size, style);
}


/*!
 * cOperatorPanel creator
 */

bool cOperatorPanel::Create( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
////@begin cOperatorPanel creation
    SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    wxPanel::Create( parent, id, pos, size, style );

    CreateControls();
    Centre();
////@end cOperatorPanel creation
    return true;
}


/*!
 * cOperatorPanel destructor
 */

cOperatorPanel::~cOperatorPanel()
{
////@begin cOperatorPanel destruction
////@end cOperatorPanel destruction
}


/*!
 * Member initialisation
 */

void cOperatorPanel::Init()
{
////@begin cOperatorPanel member initialisation
////@end cOperatorPanel member initialisation
}


/*!
 * Control creation for cOperatorPanel
 */

void cOperatorPanel::CreateControls()
{    
////@begin cOperatorPanel content construction
////@end cOperatorPanel content construction
}


/*!
 * Should we show tooltips?
 */

bool cOperatorPanel::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap cOperatorPanel::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin cOperatorPanel bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end cOperatorPanel bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon cOperatorPanel::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin cOperatorPanel icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end cOperatorPanel icon retrieval
}
