/////////////////////////////////////////////////////////////////////////////
// Name:        mainpanel.h
// Purpose:     
// Author:      Anthemion Software Ltd
// Modified by: 
// Created:     16/04/2015 18:09:50
// RCS-ID:      
// Copyright:   (c) Anthemion Software Ltd
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 16/04/2015 18:09:50

#ifndef _MAINPANEL_H_
#define _MAINPANEL_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "mainpanel.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MAINPANEL 10000
#define ID_BUTTON_DATESET 10007
#define ID_BUTTON_ENFORCEMENTSET 10001
#define ID_BUTTON_CAMERASET 10002
#define ID_BUTTON_OPERATORSET 10003
#define ID_BUTTON_FILEMNG 10004
#define ID_BUTTON_ENFORCEMENT 10001
#define ID_BUTTON5 10006
#define SYMBOL_MAINPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_MAINPANEL_TITLE _("MainPanel")
#define SYMBOL_MAINPANEL_IDNAME ID_MAINPANEL
#define SYMBOL_MAINPANEL_SIZE wxSize(400, 300)
#define SYMBOL_MAINPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * MainPanel class declaration
 */

class MainPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( MainPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    MainPanel();
    MainPanel( wxWindow* parent, wxWindowID id = SYMBOL_MAINPANEL_IDNAME, const wxPoint& pos = SYMBOL_MAINPANEL_POSITION, const wxSize& size = SYMBOL_MAINPANEL_SIZE, long style = SYMBOL_MAINPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MAINPANEL_IDNAME, const wxPoint& pos = SYMBOL_MAINPANEL_POSITION, const wxSize& size = SYMBOL_MAINPANEL_SIZE, long style = SYMBOL_MAINPANEL_STYLE );

    /// Destructor
    ~MainPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin MainPanel event handler declarations

////@end MainPanel event handler declarations

////@begin MainPanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end MainPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin MainPanel member variables
////@end MainPanel member variables
};

#endif
    // _MAINPANEL_H_
